name: carsharing
description: "A car sharing application with user and driver roles."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  email_validator: ^2.1.17
  dropdown_search: ^5.0.6
  intl: ^0.19.0
  http: ^1.2.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0

  geolocator: ^10.0.0
  permission_handler: ^11.4.0
  flutter_map_marker_popup: ^5.0.0
  confetti: ^0.7.0
  
  # REST Backend Integration
  dio: ^5.4.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.3
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1
  flutter_secure_storage: ^9.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
