const List<String> germanCities = [
  'Berlin',
  'Hamburg',
  'Munich',
  'Cologne',
  'Frankfurt am Main',
  'Stuttgart',
  'Düsseldorf',
  'Dortmund',
  'Essen',
  'Leipzig',
  'Bremen',
  'Dresden',
  'Hanover',
  'Nuremberg',
  'Duisburg',
  'Bochum',
  'Wuppertal',
  'Bielefeld',
  'Bonn',
  'Münster',
  'Karlsruhe',
  'Mannheim',
  'Augsburg',
  'Wiesbaden',
  'Gelsenkirchen',
  'Mönchengladbach',
  'Braunschweig',
  'Chemnitz',
  'Kiel',
  'Aachen',
  'Halle (Saale)',
  'Magdeburg',
  'Freiburg im Breisgau',
  'Krefeld',
  'Lübeck',
  'Oberhausen',
  'Erfurt',
  'Mainz',
  'Rostock',
  'Kassel',
  'Hagen',
  'Hamm',
  'Saarbrücken',
  'Mülheim an der Ruhr',
  'Potsdam',
  'Ludwigshafen am Rhein',
  'Oldenburg',
  'Leverkusen',
  'Osnabrück',
  'Solingen',
  'Heidelberg',
  'Herne',
  'Neuss',
  'Darmstadt',
  'Paderborn',
  'Regensburg',
  'Ingolstadt',
  'Würzburg',
  'Fürth',
  'Wolfsburg',
  'Offenbach am Main',
  'Ulm',
  'Heilbronn',
  'Pforzheim',
  'Göttingen',
  'Bottrop',
  'Trier',
  'Recklinghausen',
  'Reutlingen',
  'Bremerhaven',
  'Koblenz',
  'Bergisch Gladbach',
  'Jena',
  'Remscheid',
  'Erlangen',
  'Moers',
  'Siegen',
  'Hildesheim',
  'Salzgitter',
  'Cottbus',
  'Gera',
  'Zwickau',
]; 