// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA--oetZ6qTZl1UtibFGgpWgR1QpPNdzjI',
    appId: '1:1021345010198:web:1389371a7bfab161519b37',
    messagingSenderId: '1021345010198',
    projectId: 'carshare-3dc21',
    authDomain: 'carshare-3dc21.firebaseapp.com',
    storageBucket: 'carshare-3dc21.firebasestorage.app',
    measurementId: 'G-HNEHREFVLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdsExad-NoQ6ioNVo-shsKWmxjZefeJ8g',
    appId: '1:1021345010198:android:6cb97298fe1c9ccb519b37',
    messagingSenderId: '1021345010198',
    projectId: 'carshare-3dc21',
    storageBucket: 'carshare-3dc21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNVCag9sAbeqsKdST4o2iv0otgAH-UJsY',
    appId: '1:1021345010198:ios:e4c8c42006b4c633519b37',
    messagingSenderId: '1021345010198',
    projectId: 'carshare-3dc21',
    storageBucket: 'carshare-3dc21.firebasestorage.app',
    iosClientId: '1021345010198-6n7bfckioks6o34uc8apv4fdslcg2q05.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNVCag9sAbeqsKdST4o2iv0otgAH-UJsY',
    appId: '1:1021345010198:ios:e4c8c42006b4c633519b37',
    messagingSenderId: '1021345010198',
    projectId: 'carshare-3dc21',
    storageBucket: 'carshare-3dc21.firebasestorage.app',
    iosClientId: '1021345010198-6n7bfckioks6o34uc8apv4fdslcg2q05.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA--oetZ6qTZl1UtibFGgpWgR1QpPNdzjI',
    appId: '1:1021345010198:web:a810893dfff205dd519b37',
    messagingSenderId: '1021345010198',
    projectId: 'carshare-3dc21',
    authDomain: 'carshare-3dc21.firebaseapp.com',
    storageBucket: 'carshare-3dc21.firebasestorage.app',
    measurementId: 'G-5PXYS93CZZ',
  );

}